import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import RecommendationCard from "../components/RecommendationCard";
import { EmptyState, ErrorState, Spinner } from "../components/common";
import { api, ApiError } from "../services/api";
import type { ContentRecommendation, Priority } from "../types";

const priorityOrder: Priority[] = ["high", "medium", "low"];
const priorityLabels: Record<Priority, string> = { high: "High priority", medium: "Medium priority", low: "Low priority" };

export default function RecommendationsView() {
  const { profileUuid } = useParams<{ profileUuid: string }>();
  const [recs, setRecs] = useState<ContentRecommendation[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  async function load() {
    if (!profileUuid) return;
    setLoading(true);
    setError(null);
    try {
      const data = await api.getRecommendations(profileUuid);
      setRecs(data);
    } catch (err) {
      setError(err instanceof ApiError ? err.message : "Failed to load recommendations");
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    load();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [profileUuid]);

  return (
    <div className="flex flex-col gap-6">
      <div>
        <h1 className="font-display text-2xl font-bold text-ink">Content recommendations</h1>
        <p className="mt-1 text-sm text-muted">
          Generated by the Content Recommendation Agent for queries where you aren't currently visible.
        </p>
      </div>

      {loading && <Spinner label="Loading recommendations…" />}
      {!loading && error && <ErrorState message={error} onRetry={load} />}
      {!loading && !error && recs.length === 0 && (
        <EmptyState
          title="No recommendations yet"
          description="Run the pipeline from the profile overview to generate content recommendations for visibility gaps."
        />
      )}

      {!loading &&
        !error &&
        priorityOrder.map((priority) => {
          const group = recs.filter((r) => r.priority === priority);
          if (group.length === 0) return null;
          return (
            <div key={priority}>
              <h2 className="mb-3 font-display text-sm font-semibold uppercase tracking-wide text-muted">
                {priorityLabels[priority]} · {group.length}
              </h2>
              <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">
                {group.map((rec) => (
                  <RecommendationCard key={rec.recommendation_uuid} rec={rec} />
                ))}
              </div>
            </div>
          );
        })}
    </div>
  );
}
